### ISSUE TITLE
RSVP

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/ttdevops#3]
So far we have gotten positives from 
@kevinali1
@stephentnt
@chrisdev
@metasansana 

We also have maybes from Jonathan Eligon & Simeon Wu-Kwai. Unfortunately the latter two are not on github 

Feel free to invite other folks but the office can only comfortably accommodate a max of 6 maybe 8 persons

**Comment by chrisdev** [comment]
@stephentnt wants us to add Lochan Mungal lmmvp@hotmail.com to the list

**Comment by metasansana** [comment]
Hello, 

Sign me up too please.

@metasansana

**Comment by hezcaby** [comment]
Sign me up

**Comment by chrisdev** [comment]
@metasansana @hezcaby @stephentnt We have to postpone due to my current illness. I'm thinking late January early February?

**Comment by metasansana** [comment]
No problem, just let me know when you come up with a date. Hope you feel better soon.

**Comment by hezcaby** [comment]
Recently installed Ubuntu and trying to move some of my .NET/MSSQL projects
to python/PostgreSQL.

I'm sure no matter what time you hold it I will be happy to join.

**Comment by chrisdev** [comment]
@hezcaby @metasansana @stephentnt @kevinali1 what do you guys think about March 7.  That's the Friday after carnival?

**Comment by kevinali1** [comment]
Works for me...

**Comment by stephentnt** [comment]
I'm in Tobago from Ash Wednesday till the following Monday.

**Comment by chrisdev** [comment]
Ok @stephentnt what about the next Friday. 2014-03-14

**Comment by stephentnt** [comment]
That works for me!

**Comment by chrisdev** [comment]
Hey @swukwai are you still interested in attending

**Comment by chrisdev** [comment]
Ok as the day approaches i'm getting requests for a postponement :anguished:
What do you guys think about the 2013-03-21?

**Comment by kevinali1** [comment]
Sounds perfect for me...

**Comment by swukwai** [comment]
What time you planning on having this?  Later better for me.

**Comment by chrisdev** [comment]
@swukwai its whole day!!  about 8am to 6pm

**Comment by metasansana** [comment]
I can work with that.  What time?

On 03/10/2014 02:02 PM, Kevin Ali wrote:

> Sounds perfect for me...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chrisdev/ttdevops/issues/3#issuecomment-37213732.

## 

Regards,

Lasana Murray (Mr.)
Founder
Trinistorm
http://trinistorm.org

**Comment by swukwai** [comment]
Ok I'm on GitHub now.  Don't you people have work on Friday?  Any Saturday is fine with me as I also have classes on Friday.

**Comment by chrisdev** [comment]
@metasansana @swukwai @stephentnt @kevinali1 Well some of us have stuff to do on saturdays.
If it's saturday then we could start around  1 ?

**Comment by stephentnt** [comment]
Saturdays are alright with me once I know which one beforehand and yes,
later is better.

**Comment by chrisdev** [comment]
Ok  @kevinali1@stephentnt @chrisdev @metasansana @swukwai @Interxect can we agree to 28th March at 2p.m at ChrisDev headquarters in Tunapuna? I'll do a blog post about the proposed agenda etc., what to install before you come and the fact that there will be food.

**Comment by kevinali1** [comment]
Yes that sounds good to me.

**Comment by chrisdev** [comment]
Hey they tell met that that it should be Saturday 29th March

**Comment by kevinali1** [comment]
either day can work for me

**Comment by stephentnt** [comment]
That's good for me.

**Comment by chrisdev** [comment]
@metasansana @stephentnt @kevinali1 @swukwai  @neffmau5 just to confirm its this Saturday from about 2pm

**Comment by kevinali1** [comment]
game

**Comment by metasansana** [comment]
I can show up, where can I get more details on the event?

**Comment by chrisdev** [comment]
@metasansana here are some details on the event. So far we have 5/6 firm commitments (including yourself) we only have physical space for one or maybe two persons. 

The workshop will take place on Saturday 29th March beginning at around 1pm . 
**Location** ChrisDev, A3 St. Benedicts Gardens Tunapuna

**Agenda:**
    - Linux command line.  
    - Git for system administrators 
    - Getting started with Vagrant
    - Introduction to DevOps with Ansiable
    - Cloud services featuring Digital Ocean

We also have some Raspberry PIs that we could set up an use

*\* Will there be food?**
Yes @swukwai is going way out to ensure that the food is way over the top :dancers:

**Comment by chrisdev** [comment]
Hey everybody can we all just confirm attendance so we can estimate for the food/drinks

**Comment by chrisdev** [comment]
Just reply on this thread with a +1.  
So far we have firm commitments from: 
:+1: @kevinali1 
:+1:  @stephentnt 
:+1:  @swukwai 
:+1:  @stephentnt 
:+1:  @metasansana

**Comment by kevinali1** [comment]
+1

**Comment by chrisdev** [comment]
As we don't want to waste a lot for time downloading VirtualBox and setting up Vagrant etc. So please do  following  **before** you arrive at the Workshop:
- Install [VirtualBox](https://www.virtualbox.org/wiki/Downloads)
- Download and install [Vagrant](http://www.vagrantup.com/downloads)  and add at least one box `vagrant box add hashicorp/precise32` before you get here. 
- Check out the GitHub Git tutorial (or some other resource) if you are a bit rusty with git
- Of install git on you laptop if you don't have it. Of course you wii require a GitHub account
- You should probably install [Ansible](http://docs.ansible.com/intro_installation.html)
- If you'd like to experiment with DigitalOcean then you should join so you can get the necessary credentials

And yes you need to walk with your own Notebook Computer that is WiFi enabled :smiling_imp:

**Comment by chrisdev** [comment]
@neffmau5 do we have +1 from you?

**Comment by metasansana** [comment]
@chrisdev  Where is St. Benedicts Gardens is this up mount St. Benedict? :/

**Comment by chrisdev** [comment]
Too Tunapuna rd. call 221-  6277 or 773 4644 for directions

**Comment by kevinali1** [comment]
Hey guys, 
- thanks again for the session on Saturday. It was fun. Chris and Simian[sic?] thanks for the food.
- Lasana was asking about the GUI for ansible. Chris mentioned Ansible tower, but you have to pay for it. It seems to be free for up to 10 boxes... http://www.ansible.com/pricing#guru

**Comment by chrisdev** [comment]
Thanks @kevinali1  i'm sure @swukwai (Simeon) will be pleased
BTW Here's a link about how this guys uses Ansible and Docker http://thechangelog.com/tagged/python/

**Comment by metasansana** [comment]
Just want to echo what Kevin said. Thanks!

Thanks for the link too guys.

On 03/31/2014 10:51 AM, Christopher Clarke wrote:

> Thanks @kevinali1 https://github.com/kevinali1 i'm sure @swukwai
> https://github.com/swukwai (Simeon) will be pleased
> BTW Here's a link about how this guys uses Ansible and Docker
> http://thechangelog.com/tagged/python/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chrisdev/ttdevops/issues/3#issuecomment-39097204.

## 

Regards,

Lasana Murray (Mr.)
Founder
Trinistorm
http://trinistorm.org

**Comment by metasansana** [comment]
This is the forum I was telling you guys about:

https://groups.google.com/forum/#!forum/silicon_islands

Request to join and we will add you.

On 03/31/2014 10:51 AM, Christopher Clarke wrote:

> Thanks @kevinali1 https://github.com/kevinali1 i'm sure @swukwai
> https://github.com/swukwai (Simeon) will be pleased
> BTW Here's a link about how this guys uses Ansible and Docker
> http://thechangelog.com/tagged/python/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chrisdev/ttdevops/issues/3#issuecomment-39097204.

## 

Regards,

Lasana Murray (Mr.)
Founder
Trinistorm
http://trinistorm.org

**Comment by stephentnt** [comment]
Is it interesting to non-developers or is it all code?

**Comment by metasansana** [comment]
So far barely any code talk actually.

On 04/02/2014 12:07 PM, stephentnt wrote:

> Is it interesting to non-developers or is it all code?
> 
> On Wed, Apr 2, 2014 at 12:02 PM, Lasana Murray
> notifications@github.comwrote:
> 
> > This is the forum I was telling you guys about:
> > 
> > https://groups.google.com/forum/#!forum/silicon_islands
> > 
> > Request to join and we will add you.
> > 
> > On 03/31/2014 10:51 AM, Christopher Clarke wrote:
> > 
> > > Thanks @kevinali1 https://github.com/kevinali1 i'm sure @swukwai
> > > https://github.com/swukwai (Simeon) will be pleased
> > > BTW Here's a link about how this guys uses Ansible and Docker
> > > http://thechangelog.com/tagged/python/
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/chrisdev/ttdevops/issues/3#issuecomment-39097204.
> > 
> > ## 
> > 
> > Regards,
> > 
> > Lasana Murray (Mr.)
> > Founder
> > Trinistorm
> > http://trinistorm.org
> > 
> > ## 
> > 
> > Reply to this email directly or view it on
> > GitHubhttps://github.com/chrisdev/ttdevops/issues/3#issuecomment-39348663
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chrisdev/ttdevops/issues/3#issuecomment-39349318.

## 

Regards,

Lasana Murray (Mr.)
Founder
Trinistorm
http://trinistorm.org

**Comment by stephentnt** [comment]
I guess I can lurk

**Comment by metasansana** [comment]
Should this issue be considered resolved now?

**Comment by chrisdev** [comment]
👍🏼
